name: Semantic Release
on:
  push:
    branches: [ $default-branch, dev ]

jobs:
  call-workflow:
    uses: fr33Coders/.github/.github/workflows/ReusableRelease.yml@main
    secrets:
      github-token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

