name: Semantic Release
on:
  push:
    branches: [ $default-branch, dev ]

jobs:
  call-workflow:
    uses: fr33Coders/.github/reusable-workflows/ReusableRelease.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

