name: Semantic Release
on:
  push:
    branches: [ main, dev ]

jobs:
  call-workflow:
    uses: fr33Coders/.github/reusable-workflows/ReusableRelease.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

