name: Semantic Release
on:
  push:
    branches: [ main, master, dev ]

jobs:
  call-workflow:
    uses: fr33Coders/.github/.github/workflows/ReusableRelease.yml@dev
    secrets:
      GITHUB: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

