name: Semantic Release
on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  call-workflow-passing-data:
    uses: fr33Coders/.github/workflows/ReusableRelease.yml@v1
    with:
      secrets:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

